config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

todo/urls.py
from django.urls import path, include
from .views import *

app_name = 'todo'

urlpatterns = [
    path('', index, name='todo_list'),
    path('update/<str:pk>', update, name='todo_update'),
    path('delete/<str:pk>', delete, name='todo_delete'),
]

todo/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

todo/forms.py
from django import forms
from django.forms import ModelForm
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

todo/views.py
from django.shortcuts import render, redirect
from .models import Task
from .forms import TaskForm


def index(request):
    template = 'todo/index.html'
    tasks = Task.objects.all()
    form = TaskForm()

    if request.method == 'POST':

        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/')

    context = {
        'tasks': tasks,
        'task_form': TaskForm,
    }
    return render(request, template_name=template, context=context)


def update(request, pk):
    template = 'todo/update.html'
    task = Task.objects.get(id=pk)
    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {
        'task': task,
        'task_form': form,
    }
    return render(request, template_name=template, context=context)


def delete(request, pk):
    template = 'todo/delete.html'

    task = Task.objects.get(id=pk)
    if request.method == 'POST':
        if 'delete_task' in request.POST:
            task.delete()
            return redirect('/')

        if 'cancel_task' in request.POST:
            return redirect('/')
    context = {
        'task': task,
    }

    return render(request, template_name=template, context=context)

templates/todo/delete.html
<html>
    <head>
        <title>
            Homepage
        </title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

        <style>

            body{
                background-color: #638CB8;
            }

            input{
                width: 100%;
                padding: 12px 20px;
                margin: 8px 0;
                box-sizing: border-box;
            }

            input::placeholder {
              color: #d3d3d3;
            }

            .submit{
                background-color: #6BA3E8;
            }

            .center-column{
                width:600px;
                margin: 20px auto;
                padding:20px;
                background-color: #fff;
                border-radius: 3px;
                box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
            }

            .item-row{
                background-color: #906abd;
                margin: 10px;
                padding: 20px;
                border-radius: 3px;
                color: #fff;
                font-size: 16px;
                box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
            }

            .btn-danger{
                background-color: #ffae19;
                border-color: #e59400;
            }

        </style>

    </head>
    <body>
        <div class="center-column ">
            <h1>Todo List</h1>

            <div class="todo-list">
                <span>are you sure you want to delete the below task?</span>
                <p align="center"><b>{{task}}</b></p>

                <form action="" method="POST">
                    {% csrf_token %}
                    <input class="btn btn-info" name="cancel_task" value="Cancel" type="submit">
                </form>
                <form action="" method="POST">
                    {% csrf_token %}
                    <input class="btn btn-danger" name="delete_task" value="Delete" type="submit">
                </form>

            </div>


        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    </body>
</html>

templates/todo/index.html
<html>
    <head>
        <title>
            Homepage
        </title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

        <style>

            body{
                background-color: #638CB8;
            }

            input{
                width: 100%;
                padding: 12px 20px;
                margin: 8px 0;
                box-sizing: border-box;
            }

            input::placeholder {
              color: #d3d3d3;
            }

            .submit{
                background-color: #6BA3E8;
            }

            .center-column{
                width:600px;
                margin: 20px auto;
                padding:20px;
                background-color: #fff;
                border-radius: 3px;
                box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
            }

            .item-row{
                background-color: #906abd;
                margin: 10px;
                padding: 20px;
                border-radius: 3px;
                color: #fff;
                font-size: 16px;
                box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
            }

            .btn-danger{
                background-color: #ffae19;
                border-color: #e59400;
            }

        </style>

    </head>
    <body>
        <div class="center-column ">
            <h1>Todo List</h1>

            <div class="todo-list">
                <form action="/" method="POST">
                    {% csrf_token %}
                    {{task_form.title}}
                    <input class="btn btn-info" name="create_task" value="Create" type="submit">
                </form>
                {% for task in tasks %}

                    <div class="item-row">
                        <a class="btn btn-sm btn-info" href="{% url 'todo:todo_update' task.pk %}">Edit </a>
                        <a class="btn btn-sm btn-danger" href="{% url 'todo:todo_delete' task.pk %}">Delete </a>
                        {% if task.completed %}
                            <s>{{task.title}}</s>
                        {% else %}
                            {{task.title}}
                        {% endif %}
                    </div>
                {% endfor %}
            </div>


        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    </body>
</html>

templates/todo/update.html
<html>
    <head>
        <title>
            Homepage
        </title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

        <style>

            body{
                background-color: #638CB8;
            }

            input{
                width: 100%;
                padding: 12px 20px;
                margin: 8px 0;
                box-sizing: border-box;
            }

            input::placeholder {
              color: #d3d3d3;
            }

            .submit{
                background-color: #6BA3E8;
            }

            .center-column{
                width:600px;
                margin: 20px auto;
                padding:20px;
                background-color: #fff;
                border-radius: 3px;
                box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
            }

            .item-row{
                background-color: #906abd;
                margin: 10px;
                padding: 20px;
                border-radius: 3px;
                color: #fff;
                font-size: 16px;
                box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
            }

            .btn-danger{
                background-color: #ffae19;
                border-color: #e59400;
            }

        </style>

    </head>
    <body>
        <div class="center-column ">
            <h1>Todo List</h1>

            <div class="todo-list">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{task_form.as_p}}
                    <input class="btn btn-info" name="update_task" value="Update" type="submit">
                </form>

            </div>


        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    </body>
</html>